#+TITLE: jacob-berwalt

A simple tool to convert MediaWiki articles and books to beautiful
TeX. Originally written to typeset the wiki book [[https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks][Mathe für Nicht-Freaks]].

For those curious about the name of the project, Jacob Berwalt was a
printer in the 16th century. He printed the first edition of Adam Ries'es
famous German book on arithmetic "Rechenung nach der lenge, auff den
Linihen vnd Feder". This book had such a big impact on the the German
language and mathematics, that 'nach Adam Riese' is still a common phrase
to express the use of simple arithmetic. We think that not only authors
deserve credit, but also editors and printers.

** Usage
*** command line interface
#+BEGIN_SRC sh
./jacob-berwalt URL PATH
#+END_SRC
where =URL= is a MediaWiki page and =PATH= is a list of headlines.
The program will download the page and step down in the table of contents
following the headlines.
**** Download the book "Analysis 1"
#+BEGIN_SRC sh
./jacob-berwalt.rb "Mathe für Nicht-Freaks: Sitemap" "Analysis 1"
#+END_SRC
**** Download the chapter "Stetigkeit" from "Analysis 1"
#+BEGIN_SRC sh
./jacob-berwalt.rb "Mathe für Nicht-Freaks: Sitemap" "Analysis 1" "Stetigkeit"
#+END_SRC
**** Download the article "Satz vom Minimum und Maximum" directly
#+BEGIN_SRC sh
./jacob-berwalt.rb "Mathe für Nicht-Freaks: Satz vom Minimum und Maximum"
#+END_SRC
Note: in MFNF, this doesn't work for books and chapters, because their
raw pages are empty (generated by a Lua function).

** The TODO list
*** change from regex matching to real parsing
- stack of matched opening delimiters
- a function flip that converts e.g. '((' to '))' and '<math>' to '</math>'
- one regex for opening mediawiki delimiters, one for HTML ones
- a function String.to_tex( surrounding_delimiter ), e.g.
  "foo".to_tex("<math>") => "$foo$"
- after a match, go to the next opening or closing construct, whatever is closer
- at a closing construct, invoke body.to_tex( stack.pop )
*** generic user defined blocks
when the the String.to_tex("{{") function finds no no applicable standard
interpretation of a block type, look up in a table of user defined parser
methods that can handle e.g. "Mathe für Nicht-Freaks: Vorlage:Definition".
*** Crawling and user interaction
**** Give usefule feedback if books/articles aren't found
**** Handle broken pages/link loops
